[toolchain]
channel = "1.94.1"

components = [
	"cargo",
	"clippy",
	"llvm-tools",
	"rust-analyzer",
	"rust-docs",
	"rust-src",
	"rustfmt",
]
targets = [
	"x86_64-unknown-linux-gnu",
	# gh-sync:keep-start
	# gh-sync:keep-end
]
profile = "default"
