# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: "Rust Security Audit"
description: "Run cargo audit to check for vulnerable dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false

    - name: Install cargo-audit
      uses: taiki-e/install-action@3d7d7cd5ac7f994c1892ae0c06165095b9139094 # v2.85.1
      with:
        tool: cargo-audit

    - name: Run audit
      shell: bash
      run: cargo audit
